const { Resend } = require('resend');
const PDFDocument = require('pdfkit');

const resend = new Resend(process.env.RESEND_API_KEY);

module.exports = async (req, res) => {
    if (req.method !== 'POST') {
        return res.status(405).json({ error: 'Method not allowed' });
    }

    try {
        const data = req.body;
        const { companyName, fullName, email } = data;

        if (!companyName || !fullName || !email) {
            return res.status(400).json({ error: 'Missing core contact information' });
        }

        // 1. Generate PDF in memory
        const pdfBuffer = await new Promise((resolve, reject) => {
            const doc = new PDFDocument({ margin: 50 });
            const chunks = [];

            doc.on('data', chunk => chunks.push(chunk));
            doc.on('end', () => resolve(Buffer.concat(chunks)));
            doc.on('error', reject);

            // Header
            doc.fontSize(24).font('Helvetica-Bold').text('MOOOD.STUDIO', { letterSpacing: 2 });
            doc.fontSize(10).font('Helvetica').text('BRANDING QUOTE REQUEST', { characterSpacing: 1 });
            doc.moveDown(2);
            doc.rect(50, doc.y, 500, 1).fill('#000000');
            doc.moveDown(2);

            // Contact Info Section
            doc.fontSize(14).font('Helvetica-Bold').text('01. CONTACT INFORMATION');
            doc.moveDown(0.5);
            doc.fontSize(10).font('Helvetica-Bold').text('Company: ', { continued: true }).font('Helvetica').text(data.companyName || 'N/A');
            doc.font('Helvetica-Bold').text('Contact Name: ', { continued: true }).font('Helvetica').text(data.fullName || 'N/A');
            doc.font('Helvetica-Bold').text('Role: ', { continued: true }).font('Helvetica').text(data.role || 'N/A');
            doc.font('Helvetica-Bold').text('Email: ', { continued: true }).font('Helvetica').text(data.email || 'N/A');
            doc.moveDown(2);

            // Business Profile
            doc.fontSize(14).font('Helvetica-Bold').text('02. BUSINESS PROFILE');
            doc.moveDown(0.5);
            doc.fontSize(10).font('Helvetica-Bold').text('Brand Name: ', { continued: true }).font('Helvetica').text(data.brandName || 'N/A');
            doc.font('Helvetica-Bold').text('Target Audience: ', { continued: true }).font('Helvetica').text(data.targetAudience || 'N/A');
            doc.font('Helvetica-Bold').text('Brand Values: ', { continued: true }).font('Helvetica').text(data.brandValues || 'N/A');
            doc.font('Helvetica-Bold').text('Description:');
            doc.font('Helvetica').text(data.businessDescription || 'N/A', { width: 500, align: 'justify' });
            doc.moveDown(2);

            // Identity Diagnosis
            doc.fontSize(14).font('Helvetica-Bold').text('03. IDENTITY DIAGNOSIS');
            doc.moveDown(0.5);
            doc.fontSize(10).font('Helvetica-Bold').text('Status: ', { continued: true }).font('Helvetica').text(data.projectStatus || 'N/A');
            doc.font('Helvetica-Bold').text('Problem Statement:');
            doc.font('Helvetica').text(data.problemStatement || 'N/A', { width: 500 });
            doc.moveDown(0.5);
            doc.font('Helvetica-Bold').text('Competitive Advantage:');
            doc.font('Helvetica').text(data.competitiveAdvantage || 'N/A', { width: 500 });
            doc.moveDown(2);

            // Creative Scope
            doc.fontSize(14).font('Helvetica-Bold').text('04. CREATIVE SCOPE');
            doc.moveDown(0.5);
            doc.fontSize(10).font('Helvetica-Bold').text('Primary Applications: ', { continued: true }).font('Helvetica').text(data.primaryApplications || 'N/A');
            doc.font('Helvetica-Bold').text('Color Preferences: ', { continued: true }).font('Helvetica').text(data.colorPreferences || 'N/A');
            doc.font('Helvetica-Bold').text('Preferred Logo Style: ', { continued: true }).font('Helvetica').text(data.logo_style || 'Not selected');
            doc.moveDown(2);

            // Logistics
            doc.fontSize(14).font('Helvetica-Bold').text('05. LOGISTICS');
            doc.moveDown(0.5);
            doc.fontSize(10).font('Helvetica-Bold').text('Visual Inspiration: ', { continued: true }).font('Helvetica').text(data.visualInspiration || 'N/A');
            doc.font('Helvetica-Bold').text('Launch Date: ', { continued: true }).font('Helvetica').text(data.launchDate || 'N/A');
            doc.font('Helvetica-Bold').text('Investment Range: ', { continued: true }).font('Helvetica').text(data.investmentRange || 'N/A');
            doc.moveDown(0.5);
            doc.font('Helvetica-Bold').text('Additional Comments:');
            doc.font('Helvetica').text(data.additionalComments || 'N/A', { width: 500 });

            // Footer
            doc.fontSize(8).fill('#666666').text('Generated by Moood.Studio Agency Onboarding System', 50, 750, { align: 'center' });

            doc.end();
        });

        // 2. Send email via Resend
        const { data: emailData, error } = await resend.emails.send({
            from: 'Moood Studio <notifications@moood.studio>',
            to: ['alberto.contreras@gmail.com'],
            subject: `Branding Quest: ${companyName} (${fullName})`,
            html: `
                <div style="font-family: sans-serif; color: #111;">
                    <h2 style="border-bottom: 2px solid #000; padding-bottom: 10px;">New Branding Questionnaire</h2>
                    <p>A new client has completed the branding questionnaire. A detailed PDF summary is attached.</p>
                    <p><strong>Company:</strong> ${companyName}</p>
                    <p><strong>Client:</strong> ${fullName}</p>
                    <p><strong>Email:</strong> ${email}</p>
                </div>
            `,
            attachments: [
                {
                    filename: `Moood_Quote_${companyName.replace(/\s+/g, '_')}.pdf`,
                    content: pdfBuffer,
                },
            ],
        });

        if (error) {
            console.error('Email error:', error);
            return res.status(500).json({ error: 'Failed to send email' });
        }

        return res.status(200).json({ success: true, message: 'Quote request sent successfully' });

    } catch (err) {
        console.error('API Error:', err);
        return res.status(500).json({ error: 'Internal server error', details: err.message });
    }
};
